import {parseMatrix,format,multiply,transpose,hadamard,kron,sparsity,classifyStructure,memoryModel,traceCell,estimateOps,normalizeRows,slice} from './engine.js';
import {EXAMPLES} from './examples.js';
const $=s=>document.querySelector(s); const Ael=$('#A'), Bel=$('#B'), out=$('#out'), stats=$('#stats'), extra=$('#extra');
function load(key){const x=EXAMPLES[key];Ael.value=x.A.map(r=>r.join(' ')).join('\n');Bel.value=x.B.map(r=>r.join(' ')).join('\n');run()}
document.querySelectorAll('[data-example]').forEach(b=>b.onclick=()=>load(b.dataset.example));
function safe(fn){try{fn()}catch(e){out.textContent='Error: '+e.message;stats.innerHTML='';extra.innerHTML=''}}
function matrixViz(A){return `<div class="viz">${A.flat().map(v=>`<div class="cell ${v===0?'zero':''}">${Number(v.toFixed?.(3)??v)}</div>`).join('')}</div>`}
function run(){safe(()=>{const A=parseMatrix(Ael.value),B=parseMatrix(Bel.value),mode=document.body.dataset.mode; let C,html=''; if(mode==='matmulx'){C=multiply(A,B); const o=estimateOps(A,B); out.textContent=format(C);stats.innerHTML=`<div class=stat><span>Dense multiplies</span><b>${o.denseMult}</b></div><div class=stat><span>Sparse multiplies</span><b>${o.sparseMult}</b></div><div class=stat><span>Skipped</span><b>${o.skipped}</b></div>`;html='<h2>Output structure</h2>'+matrixViz(C)} else if(mode==='matrixmorph'){const op=$('#operation').value; if(op==='transpose') C=transpose(A); if(op==='hadamard') C=hadamard(A,B); if(op==='kron') C=kron(A,B); if(op==='normalize') C=normalizeRows(A); if(op==='slice') C=slice(A,0,Math.min(3,A.length),0,Math.min(3,A[0].length)); out.textContent=format(C);stats.innerHTML=`<div class=stat><span>Input</span><b>${A.length}×${A[0].length}</b></div><div class=stat><span>Output</span><b>${C.length}×${C[0].length}</b></div><div class=stat><span>Operation</span><b>${op}</b></div>`;html='<h2>Visual result</h2>'+matrixViz(C)} else if(mode==='sparsescope'){const s=sparsity(A),m=memoryModel(A),c=classifyStructure(A); out.textContent=JSON.stringify({sparsity:+(s*100).toFixed(2)+'%',structure:c,denseBytes:m.denseBytes,csrBytes:m.csrBytes,recommended:s>0.65?'CSR / sparse representation':'Dense representation'},null,2);stats.innerHTML=`<div class=stat><span>Sparsity</span><b>${(s*100).toFixed(1)}%</b></div><div class=stat><span>Dense</span><b>${m.denseBytes} B</b></div><div class=stat><span>CSR est.</span><b>${m.csrBytes} B</b></div>`;html='<h2>Sparsity map</h2>'+matrixViz(A)} else {C=multiply(A,B); const i=Math.min(1,C.length-1),j=0,t=traceCell(A,B,i,j);out.textContent=format(C);stats.innerHTML=`<div class=stat><span>Inspecting</span><b>C[${i},${j}]</b></div><div class=stat><span>Terms</span><b>${t.terms.length}</b></div><div class=stat><span>Result</span><b>${t.sum}</b></div>`;html='<h2>Computation trace</h2><div class=trace>'+t.terms.map(x=>`<div>A[${i},${x.k}] × B[${x.k},${j}] = ${x.a} × ${x.b} = <b>${x.product}</b></div>`).join('')+`<div><b>Sum = ${t.sum}</b></div></div>`} extra.innerHTML=html})}
$('#run').onclick=run; $('#upload').onchange=async e=>{const f=e.target.files[0]; if(f) {Ael.value=await f.text();run()}}; if($('#operation')) $('#operation').onchange=run; load('tiny');
